---

- name: Provision a Rackspace Cloud Server instance
  hosts: localhost
  gather_facts: no

  vars_prompt:
    - name: "region_name"
      prompt: "Rackspace Cloud Region"
      default: "IAD"
      private: no

    - name: "group_name"
      prompt: "Name for the group of instances (Ex. testing)"
      private: no

    - name: "instance_count"
      prompt: "Number of instances"
      default: 1
      private: no

  tasks:
    - name: ensure the instance is created
      local_action:
        module: rax
        api_key: "{{ rax_password }}"
        auto_increment: yes
        count: "{{ instance_count }}"
        #flavor: "performance1-4" # 4 GB Performance
        flavor: "6" # 8GB Standard Instance
        image: "Ubuntu 14.04 LTS (Trusty Tahr) (PVHVM)"
        files:
          /root/.ssh/authorized_keys: ~/.ssh/id_rsa.pub
        group: "{{ group_name|lower }}"
        name: "{{ group_name|lower }}-osdev%02d"
        region: "{{ region_name }}"
        state: present
        tenant_id: "{{ rax_tenant_id }}"
        username: "{{ rax_username }}"
        user_data: files/rax_user_data.txt
        wait: yes
        wait_timeout: 300 # 5 minutes
      register: raxcloud

    - name: ensure the instance is added to a host group
      local_action: add_host name={{ item.accessIPv4 }} hostname={{ item.name }} ansible_ssh_user=root ansible_ssh_private_key_file=~/.ssh/id_rsa groupname=rax
      with_items: raxcloud.instances

    - name: ensure the inventory file is created
      local_action: shell echo "{{ item.name }} ansible_ssh_host={{ item.accessIPv4 }} ansible_ssh_port=443 ansible_ssh_user=root ansible_ssh_private_key_file=~/.ssh/id_rsa" >> hosts-raxcloud-{{ group_name|lower }} #"
      with_items: raxcloud.instances

    - name: ensure instance is responding
      local_action: wait_for host={{ item.accessIPv4 }} port=443 delay=10 timeout=60
      with_items: raxcloud.instances

    - name: ensure instance report is generated
      connection: local
      local_action: template src=templates/inventory-raxcloud.html.j2 dest={{ inventory_dir }}/inventory-raxcloud-{{ group_name|lower }}.html
