---

- name: ensure the documentation repositories are present
  git: repo={{ item.url }} dest={{ documentation_install_dir }}/{{ item.name }} version={{ item.version }} depth={{ documentation_git_depth }}
  with_items: documentation_repos
