---

documentation_install_dir: /opt/stack
documentation_milestone: master
documentation_git_depth: 1

documentation_repos:
  - { name: "api-site", url: "https://github.com/openstack/api-site.git", version: "{{ documentation_milestone }}" }
  - { name: "ha-guide", url: "https://github.com/openstack/ha-guide.git", version: "{{ documentation_milestone }}" }
  - { name: "openstack-manuals", url: "https://github.com/openstack/openstack-manuals.git", version: "{{ documentation_milestone }}" }
  - { name: "operations-guide", url: "https://github.com/openstack/operations-guide.git", version: "{{ documentation_milestone }}" }
  - { name: "security-doc", url: "https://github.com/openstack/security-doc.git", version: "{{ documentation_milestone }}" }
